{
 "title": "Oddjob Upload",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Reminders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ClearMediaSet",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(reminder_ClearMediaSet_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PlayabilityBump",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(reminder_PlayabilityBump_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PotionBump",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(reminder_PotionBump_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "StorageCleanup",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(reminder_StorageCleanup_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Upload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Queue length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "max_over_time({cluster_name=\"oddjob\"} |= `Queued message count` | regexp `Queued message count: (?P<queueCount>\\d+)` | unwrap queueCount [$__auto])"
    }
   ]
  },
  {
   "title": "GlobalConnect ingestors - Otel",
   "type": "state-timeline",
   "description": "1 - ingestor busy\n0 - ingestor idle",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    { "expr": "ingester_busy", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "GlobalConnect speed - Otel",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(ingester_speed[15m]))",
     "legendFormat": "upload speed"
    }
   ]
  },
  {
   "title": "GlobalConnect upload total - Otel",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    { "expr": "sum(ingester_uploaded)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Upload total per ingester",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ingester_uploaded", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Avg speed per ingester",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 17, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "ingester_speed", "legendFormat": "{{id}}" }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Health check",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "direction": "backward",
     "expr": "max_over_time({cluster_name=\"oddjob\", environment=\"${env:text}\"} |= `Queued message count` | regexp `Queued message count: (?P<queueCount>\\d+)` | unwrap queueCount [$__auto])"
    }
   ]
  }
 ]
}