{
 "title": "Akka Phobos Metrics",
 "description": "System-wide Akka.NET metrics used for profiling Akka.NET performance. Gathered via Phobos and OpenTelemetry. Built for Phobos 2.x.",
 "tags": [
  "akka.net",
  "phobos"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "role", "label": "Role", "query": { "query": "label_values(cluster_role)" } },
   {
    "name": "address",
    "label": "address",
    "query": {
     "query": "label_values(akka_cluster_members{cluster_role=~\"$role\"},akka_address)"
    }
   },
   {
    "name": "shardRegion",
    "label": "shardRegion",
    "query": {
     "query": "label_values(akka_cluster_sharding_shards{akka_address=~\"$address\", cluster_role=~\"$role\"},region)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Cluster Size",
   "type": "stat",
   "description": "Total number of active Akka.Cluster Members.",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(avg(akka_cluster_members{status=\"Up\"}))",
     "legendFormat": "Up"
    },
    {
     "expr": "ceil(avg(akka_cluster_members{status=\"WeaklyUp\"}))",
     "legendFormat": "WeaklyUp"
    },
    {
     "expr": "ceil(avg(akka_cluster_members{status=\"Joining\"}))",
     "legendFormat": "Joining"
    },
    {
     "expr": "ceil(avg(akka_cluster_members{status=\"Leaving\"}))",
     "legendFormat": "Leaving"
    },
    {
     "expr": "ceil(avg(akka_cluster_members{status=\"Exiting\"}))",
     "legendFormat": "Exiting"
    },
    {
     "expr": "ceil(avg(akka_cluster_members{status=\"Down\"}))",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Unreachable Nodes",
   "type": "stat",
   "description": "All nodes in the cluster that are detected to be unreachable.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(avg(akka_cluster_reachable_members{status=\"False\"}))"
    }
   ]
  },
  {
   "title": "Cluster Nodes by Status",
   "type": "timeseries",
   "description": "Tracks all nodes by their membership status and reachability.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(avg by(status)(akka_cluster_members))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "ceil(avg(akka_cluster_reachable_members{status=\"False\"}))",
     "legendFormat": "Unreachable"
    }
   ]
  },
  { "title": "Logging and Error Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Cluster Logging Activity",
   "type": "timeseries",
   "description": "Total aggregate logging activity per-second for each node in an Akka.NET cluster.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(level)(ceil(irate(akka_logs_events_total{cluster_role=~\"$role\",akka_address=~\"$address\"}[$__range])))",
     "legendFormat": "{{level}} / s"
    }
   ]
  },
  {
   "title": "Exceptions by Type",
   "type": "table",
   "description": "Groups all exceptions detected in Akka.NET logs by type.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(cluster_role,akka_address,exceptiontype)(ceil(increase(akka_logs_events_total{cluster_role=~\"$role\",akka_address=~\"$address\",exceptiontype=~\".+\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Total Errors Logged",
   "type": "stat",
   "description": "Total errors logged by Akka.NET over the time window.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(akka_logs_events_total{level=\"error\",cluster_role=~\"$role\",akka_address=~\"$address\"}[$__range])))"
    }
   ]
  },
  { "title": "Actor Metrics [$role]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }, "repeat": "role" },
  {
   "title": "Total Actor Message Processing (msg/s)",
   "type": "timeseries",
   "description": "All actor message processing activity",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(ceil(irate(akka_messages_recv_msgs_total{cluster_role=~\"$role\",akka_address=~\"$address\"}[$__range])))",
     "legendFormat": "processed msgs / second"
    },
    {
     "expr": "sum(ceil(irate(akka_messages_deadletters_msgs_total{cluster_role=~\"$role\",akka_address=~\"$address\"}[$__range])))",
     "legendFormat": "deadletters / second"
    },
    {
     "expr": "sum(ceil(irate(akka_messages_unhandled_msgs_total{cluster_role=~\"$role\",akka_address=~\"$address\"}[$__range])))",
     "legendFormat": "unhandled msgs / second"
    }
   ]
  },
  {
   "title": "Total Akka.NET Actors",
   "type": "timeseries",
   "description": "The full set of Akka.NET actors running on all nodes for all roles in a cluster.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(cluster_role,akka_address)(akka_actor_live_actors{cluster_role=~\"$role\",akka_address=~\"$address\"})",
     "legendFormat": "Total Actors [{{cluster_role}} ({{akka_address}})]"
    }
   ]
  },
  {
   "title": "Total Actor Throughput (msg/s)",
   "type": "stat",
   "description": "Cumulative Akka.NET messaging throughput across all selected nodes and roles.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ceil(irate(akka_messages_recv_msgs_total{cluster_role=~\"$role\",akka_address=~\"$address\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Live Actors by Type",
   "type": "table",
   "description": "All actor counts by type.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "topk(10,sum by(actortype)(akka_actor_live_actors{cluster_role=~\"$role\",akka_address=~\"$address\"}))",
     "legendFormat": "{{actortype}} created"
    }
   ]
  },
  {
   "title": "Actor Crashes by Actor / Exception (Top 10)",
   "type": "table",
   "description": "Top 10 actor type / exception type pairs, based on the number of crashes per second observed over a 30 minute timespan.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "topk(10,sum by(actortype, exceptiontype)(rate(akka_actor_restarts_total[30m])))",
     "legendFormat": "{{actortype}},{{exceptiontype}}"
    }
   ]
  },
  {
   "title": "Akka.NET Message Throughput by Type  (Top 10)",
   "type": "bargauge",
   "description": "Akka.NET message throughput by message type.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by(messagetype)(rate(akka_messages_recv_msgs_total{cluster_role=~\"$role\",akka_address=~\"$address\"}[$__range])))",
     "legendFormat": "{{messagetype}}"
    }
   ]
  },
  {
   "title": "Akka.NET Message Totals by Type  (Top 10)",
   "type": "bargauge",
   "description": "Akka.NET message throughput by message type.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by(messagetype)(increase(akka_messages_recv_msgs_total{cluster_role=~\"$role\",akka_address=~\"$address\"}[$__range])))",
     "legendFormat": "{{messagetype}}"
    }
   ]
  },
  {
   "title": "Sharding Statistics [$shardRegion]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "repeat": "shardRegion"
  },
  {
   "title": "Shard Distribution [$shardRegion]",
   "type": "bargauge",
   "description": "Shows the distribution of $shardRegion shards across all nodes in the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(akka_address)(akka_cluster_sharding_shards{region=~\"$shardRegion\"})",
     "legendFormat": "{{akka_address}}"
    }
   ]
  },
  {
   "title": "Entity Distribution [$shardRegion]",
   "type": "bargauge",
   "description": "Shows the distribution of $shardRegion entities across all nodes in the cluster. Please note that this number reflects the total number of ALIVE entity actors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(akka_address)(akka_cluster_sharding_entities{region=~\"$shardRegion\"})",
     "legendFormat": "{{akka_address}}"
    }
   ]
  }
 ]
}