SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID(N'[dbo].[MediaSetStates]', N'U') IS NULL

CREATE TABLE [dbo].[MediaSetStates](
	[MediaSetId] [nvarchar](255) NOT NULL,
	[State] [varbinary](MAX) NOT NULL,
	[Timestamp] [datetime] NOT NULL,
CONSTRAINT [PK_MediaSetStates] PRIMARY KEY NONCLUSTERED
(
	[MediaSetId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
