SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID(N'[dbo].[MediaSetStatuses]', N'U') IS NULL

CREATE TABLE [dbo].[MediaSetStatuses](
	[MediaSetId] [nvarchar](255) NOT NULL,
	[Status] [int] NOT NULL,
    [LastActivationTime] [datetime] NOT NULL,
	[LastUpdateTime] [datetime] NOT NULL,
	[RetryCount] [int] NOT NULL,
	[Priority] [int] NOT NULL,
CONSTRAINT [PK_MediaSetStatuses] PRIMARY KEY NONCLUSTERED
(
	[MediaSetId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE CLUSTERED INDEX [IX_MediaSetStatuses_ActivationTime] ON [dbo].[MediaSetStatuses]
(
	[LastActivationTime] ASC,
	[Status] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_MediaSetStatuses_Status] ON [dbo].[MediaSetStatuses]
    (
     [Status] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
